server {
    server_name espaciokume.com.ar www.espaciokume.com.ar;

    root /var/www/kume-wellness;
    index index.html;

    access_log /var/log/nginx/espaciokume-access.log;
    error_log /var/log/nginx/espaciokume-error.log;

    location / {
        try_files $uri $uri/ =404;
    }

    gzip on;
    gzip_types text/css application/javascript;

    server_tokens off;

    listen [::]:443 ssl;
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/espaciokume.com.ar/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/espaciokume.com.ar/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    if ($host = www.espaciokume.com.ar) {
        return 301 https://$host$request_uri;
    }

    if ($host = espaciokume.com.ar) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    listen [::]:80;
    server_name espaciokume.com.ar www.espaciokume.com.ar;
    return 404;
}
